<?php

/**
 * @file
 * Contains dpi_converter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dpi_converter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dpi_converter module.
    case 'help.page.dpi_converter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a service/helper to convert the dpi of an image (jpg). Requires IMAGICK PHP extension.') . '</p>';
      return $output;

    default:
  }
}
